# Generated by Django 5.1.2 on 2024-11-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virouteapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=255)),
                ("image_path", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
