# Generated by Django 5.1.2 on 2024-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virouteapp", "0002_user_favourite_place_favplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="favplace",
            name="name",
            field=models.CharField(default="default", max_length=255),
        ),
    ]
